### PR TITLE
Added new observer example

### PR DESCRIPTION
**Pull request by mwand**
all-examples/observer-balls-and-wall .   Unlike my last PR, this one is entirely local.

### CODE REVIEW

**Comment by jon-bell** [comment]
I like this example. It might be nice to set up the activity by outlining some strawman  implementations for this that don’t follow the observer pattern: like maybe there is just a single class that has the code to simulate many balls against the wall (and it looks gross), and then we can make it even more gross looking by talking about how some balls might be bouncier than others, and have different behavior. This might help explain the value of the observer pattern here (to put the bouncing logic directly in the ball).

**Comment by jon-bell** [comment]
Also, it’s hard for me to think about a large bouncing ball simulation and not think of this 2005 Sony Bravia Ad - https://youtu.be/0_bx8bnCoiU . One of my professors in 2009 showed that ad in class in the context of talking about simulating physics, and after we were all so impressed with it he pointed out that simulating that all would have been ungodly expensive, and largely impossible to get just right (especially, for instance, the frog jumping out right around the balls) - there’s a separate making-of video that shows how they did it (with 250,000 balls, a lot of nets, and a lot of crew to collect the balls).

**Comment by franktip** [comment]
Nice example! Thanks, Mitch!

**Comment by mwand** [comment]
This is actually part of an example we used in cs5010.  In the full system,
you could drag the wall with the mouse, and also interactively add multiple
balls to the simulation.

I just looked at some of the slides for that portion of the course, and
some of them might be useful for our students now.  No time now, but I'll
share them in a little while.

**Pull request merged**
